name: Auto Deploy Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - branch: staging
            environment: Staging

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Đảm bảo fetch đầy đủ commit history (quan trọng khi cần các tag hoặc branch đầy đủ)

      - name: Print deployment info
        run: echo "Deploying to ${{ matrix.environment }} environment on branch ${{ matrix.branch }}"

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy via SSH
        env:
          SSH_PASSWORD: ${{ secrets.DEPLOY_PASSWORD }}
          USERNAME: ${{ secrets.DEPLOY_USERNAME }}
          HOST: ${{ secrets.DEPLOY_SERVER }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $USERNAME@$HOST <<EOF
          cd /var/www/site-kid365-lp
          echo "This is the staging environment" > test_env_staging.txt

          EOF
